21001 user.err CPU使用率がしきい値を超過しました（超過回数: $count_exceed / 許容回数: $threshold_count、しきい値: $threshold%、現在値: $usage_val_int%、$SCRIPT_NAME）。
11001 user.warn CPU使用率がしきい値を超過しました（超過回数: $count_exceed / 許容回数: $threshold_count、しきい値: $threshold%、現在値: $usage_val_int%、$SCRIPT_NAME）。

21002 user.err メモリ使用率がしきい値を超過しました（超過回数: $count_exceed / 許容回数: $threshold_count、しきい値: $threshold%、現在値: $usage_val_int%、$SCRIPT_NAME）。
11002 user.warn メモリ使用率がしきい値を超過しました（超過回数: $count_exceed / 許容回数: $threshold_count、しきい値: $threshold%、現在値: $usage_val_int%、$SCRIPT_NAME）。

11003 user.warn ファイルシステムの使用率がしきい値を超過しました（超過回数: $count_exceed / 許容回数: $warn_crit、しきい値: $warn_thres%、現在値: $usage_now%、ファイルシステム: $fs、$SCRIPT_NAME）。
21003 user.err ファイルシステムの使用率がしきい値を超過しました（超過回数: $count_exceed / 許容回数: $warn_crit、しきい値: $crit_thres%、現在値: $usage_now%、ファイルシステム: $fs、$SCRIPT_NAME）。