# ---- squid logs receive ----

template(name="SquidAccessLog" type="string"
         string="/mnt/log_strage/dyna_file_storage/access.log")

template(name="SquidCacheLog" type="string"
         string="/mnt/log_strage/dyna_file_storage/cache.log")

if ($programname == "squid_access") then {
    action(type="omfile" dynaFile="SquidAccessLog")
    stop
}

if ($programname == "squid_cache") then {
    action(type="omfile" dynaFile="SquidCacheLog")
    stop
}
