#### MODULES ####

module(load="imtcp")
module(load="imudp")

#### mFW,mLB REMOTE RECEIVING RULES ####
input(type="imtcp" port="514")
input(type="imudp" port="514")

# mFW,mLB のローカルログ出力形式の設定
template(name="LocalFormat" type="string"
    string="%timestamp:::date-rfc3339% %hostname% %syslogfacility-text%.%syslogseverity-text% %syslogtag%%msg:::sp-if-no-1st-sp%%msg:::drop-last-lf%\n"
)

template(name="mFWLog" type="string"
    string="/var/log/mfw.log")

template(name="mLBLog" type="string"
    string="/var/log/mlb.log")

#### mFW,mLB FORWARDING RULES ####

# ログ管理サーバへの収集ログ転送形式の設定
template(name="RelpForwardFormat" type="string"
    string="%timestamp:::date-rfc3339% %hostname% %!filename_only% %syslogfacility-text%.%syslogseverity-text% %syslogtag%%msg:::sp-if-no-1st-sp%%msg:::drop-last-lf%\n"
)

# mFW,mLB のログ管理サーバへの転送（mFW,mLBから自サーバ以外からのログ）
if $fromhost-ip != '127.0.0.1' then {
    # ファシリティ local7 は mFW で使用
    if ($syslogfacility-text == 'local7') then {
        action(type="omfile"
            dynaFile="mFWLog"
            template="LocalFormat"
        )
        set $!filename_only = "mFW_log";
    }
    # ファシリティ kern は mLB で使用
    else if ($syslogfacility-text == 'kern') then {
        action(type="omfile"
            dynaFile="mLBLog"
            template="LocalFormat"
        )
        set $!filename_only = "mLB_log";
    }

    action(type="omrelp"
        target="opelom01op1"
        port="20514"
        template="RelpForwardFormat"
        queue.filename="fwdmFWLB"
        queue.maxdiskspace="1g"
        queue.saveonshutdown="on"
        queue.type="LinkedList"
        action.resumeRetryCount="-1"
    )
}