# ---- squid logs send by RELP ----

input(type="imfile"
      File="/var/log/squid/access.log"
      Tag="squid_access"
      Severity="info"
      Facility="local5")

input(type="imfile"
      File="/var/log/squid/cache.log"
      Tag="squid_cache"
      Severity="info"
      Facility="local5")
