#### GLOBAL DIRECTIVES ####

# Where to place auxiliary files
global(workDirectory="/var/lib/rsyslog")

# ローカルログのデフォルト出力形式の設定
template(name="LocalFormat" type="string"
    string="%timestamp:::date-rfc3339% %hostname% %syslogfacility-text%.%syslogseverity-text% %syslogtag%%msg:::sp-if-no-1st-sp%%msg:::drop-last-lf%\n"
)

# デフォルト出力形式でローカルログを作成
module(load="builtin:omfile" Template="LocalFormat")

#### MODULES ####

# journaldでの入力を有効化
module(load="imjournal" UsePid="system" FileCreateMode="0644")

# ログファイルでの入力を有効化（実際のログファイルパスなどは別ファイルにて定義）
#module(load="imfile")

# RELP形式でのログ出力（転送）を有効化
module(load="omrelp")

# ログファイルでの入力の定義は別ファイル定義して以下に配置
include(file="/etc/rsyslog.d/*.conf" mode="optional")

# ============================================================
# 監査ログ（audit.log）用の共通インプット定義
# ============================================================
input(type="imfile"
    File="/var/log/audit/audit.log"
    Tag="varlog_audit"
    Severity="info"
    Facility="local2"
)

#### RULES ####

*.info;mail.none;authpriv.none;cron.none        /var/log/messages
authpriv.*                                      /var/log/secure
mail.*                                          -/var/log/maillog
cron.*                                          /var/log/cron
*.emerg                                         :omusrmsg:*
uucp,news.crit                                  /var/log/spooler
local7.*                                        /var/log/boot.log

#### STANDARD FORWARDING RULES ####

# ログ管理サーバへの収集ログ転送形式の設定
template(name="RelpForwardFormat" type="string"
    string="%timestamp:::date-rfc3339% %hostname% %!filename_only% %syslogfacility-text%.%syslogseverity-text% %syslogtag%%msg:::sp-if-no-1st-sp%%msg:::drop-last-lf%\n"
)

# /var/log/messages の転送
if $syslogseverity <= 6 and
    not ($syslogfacility-text == 'mail' or
         $syslogfacility-text == 'authpriv' or
         $syslogfacility-text == 'cron' or
         $syslogfacility-text == 'local6') then {
    set $!filename_only = "varlog_messages";
}

# /var/log/secure の転送
if $syslogfacility-text == 'authpriv' then {
    set $!filename_only = "varlog_secure";
}

# /var/log/audit/audit.log の転送
if $syslogfacility-text == 'local2' then {
    set $!filename_only = "varlog_audit";
}

# /var/log/maillog の転送
#if $syslogfacility-text == 'mail' then {
#    set $!filename_only = "varlog_maillog";
#}

# /var/log/cron の転送
#if $syslogfacility-text == 'cron' then {
#    set $!filename_only = "varlog_cron";
#}

# /var/log/spooler の転送
#if $syslogfacility-text == 'uucp' or
#   ($syslogfacility-text == 'news' and $syslogseverity-text == 'crit') then {
#    set $!filename_only = "varlog_spooler";
#}

# /var/log/boot.log の転送
#if $syslogfacility-text == 'local7' then {
#    set $!filename_only = "varlog_boot_log";
#}

action(type="omrelp"
    target="opelom01op1"
    port="20514"
    template="RelpForwardFormat"
    queue.filename="fwdDefault"
    queue.maxdiskspace="1g"
    queue.saveonshutdown="on"
    queue.type="LinkedList"
    action.resumeRetryCount="-1"
)