#!/bin/bash
#_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/
#
# Usage:
#    BasicTemplate.sh
#
# Description:
#    This script is auto-generated by template.sh.
#
# Design documents
#    None
#
#_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/
# ＜変更履歴＞
# Ver. 変更管理No. 日付        更新者       変更内容
#_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/

# shellcheck disable=SC1091
. "$(dirname "${BASH_SOURCE[0]}")/../com/logger.shrc"
. "$(dirname "${BASH_SOURCE[0]}")/../com/utils.shrc"

# runAs       root "$@"
# setLANG     utf-8

# ----------------------------------------------------------
# variables
# ----------------------------------------------------------
scope="var"

# Job status codes
JOB_OK=0  # Normal exit
JOB_WR=1  # Warning exit
JOB_ER=2  # Error exit

# Global variables
rc=${JOB_ER}
scope=""
TARGET_LIST=""

# ----------------------------------------------------------
# functions
# ----------------------------------------------------------
scope="func"

# ------------------------------------------------------------------
# 関数名　　：terminate
# 概要　　　：終了時の共通後処理を行う
# 説明　　　：
#   trap から呼び出される終了処理です。
#   必要に応じてロック解放などの後処理を実施します。
#
# 引数　　　：なし
# 戻り値　　：なし
# 使用箇所　：trap
# ------------------------------------------------------------------
terminate() {
  releaseLock
}

# ------------------------------------------------------------------
# 関数名　　：checkArgs
# 概要　　　：引数の妥当性を確認する
# 説明　　　：
#   このテンプレートをベースにした個別スクリプトで、
#   必要な引数チェック処理を実装します。
#
# 引数　　　：スクリプト引数一式
# 戻り値　　：0:正常 2:異常
# 使用箇所　：pre-process
# ------------------------------------------------------------------
checkArgs() {
  :
}

# ------------------------------------------------------------------
# 関数名　　：checkConf
# 概要　　　：設定値の妥当性を確認する
# 説明　　　：
#   このテンプレートをベースにした個別スクリプトで使用する
#   設定値や対象ファイルの妥当性確認を実装します。
#
# 引数　　　：なし
# 戻り値　　：0:正常 2:異常
# 使用箇所　：pre-process
# ------------------------------------------------------------------
checkConf() {
  :
}

# ----------------------------------------------------------
# pre-process
# ----------------------------------------------------------
scope="pre"

startLog
trap "terminate" EXIT HUP INT QUIT TERM

logOut "DEBUG" "args: [$*]"

if acquireLock; then
  logOut "INFO" "successfully locked."
else
  abort "could not acquire lock."
fi

checkArgs "$@"
checkConf

# ----------------------------------------------------------
# main-routine
# ----------------------------------------------------------
scope="main"

# 個別スクリプトで TARGET_LIST を設定して使用する
if [ -z "${TARGET_LIST}" ]; then
  logOut "ERROR" "TARGET_LIST is not set."
  exitLog "${JOB_ER}"
fi

if [ ! -f "${TARGET_LIST}" ]; then
  logOut "ERROR" "Configuration file not found: ${TARGET_LIST}"
  exitLog "${JOB_ER}"
fi

while IFS= read -r line; do
  logOut "DEBUG" "Line read - [${line}]"
  logOut "DEBUG" "Loop started turn of [ ${line} ]."

  # 個別処理をここへ実装する
  :
done < <(sed '/^#/d;/^[[:blank:]]*$/d' "${TARGET_LIST}")

rc=${JOB_OK}

# ----------------------------------------------------------
# post-process
# ----------------------------------------------------------
scope="post"

exitLog "${rc}"

